### ISSUE TITLE
FX Errors

### ISSUE THREAD

**Issue by Scillman** [BraXi/CoD4_DeathRun_1.2_Mod#4]
- [ ] Error: Could not load fx "none".
- [ ] Error: Could not load fx "sprint for longer distances.".
- [ ] Error: Could not load fx "longer breath for steadier sniper shots.".
- [ ] Error: Could not load fx "increased bullet damage.".
- [ ] Error: Could not load fx "increased hip-fire accuracy.".
- [ ] Error: Could not load fx "increased rate of fire.".
- [ ] Error: Could not load fx "faster reloading.".
- [ ] Error: Could not load fx "increased health.".

**Comment by BraXi** [comment]
fixed
