### ISSUE TITLE
xmodels missing

### ISSUE THREAD

**Issue by StefanVII** [BraXi/CoD4_DeathRun_1.2_Mod#8]
The xmodels for the characters russian_farmer, zakhaev, velinda_desert and al_asad are missing.
http://gyazo.com/858379b364109cbfa3ccc199bad3e4a9

**Comment by Scillman** [comment]
Till implemented you can get those by clicking [here](http://modsonline.com/Downloads-full-5244.html)

**Comment by BraXi** [comment]
Updated Readme.md file to contain link to this package https://github.com/BraXi/CoD4_DeathRun_1.2_Mod/blob/master/README.md#configuration--instalation
